[build]
	publish = "_site"
	command = "npm run build"

[[plugins]]
  package = "netlify-plugin-webmentions"
	[plugins.inputs]
		baseUrl = "https://blog.andrewshell.org"
		feedPath = "rss.xml"
		limit = 1

[[plugins]]
  package = "/plugins/netlify-plugin-rsscloud"
	[plugins.inputs]
		feedUrl = "https://blog.andrewshell.org/rss.xml"
		pingUrl = "https://rpc.rsscloud.io/ping"

[[headers]]
  for = "/*"
  	[headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"
  for = "/.well-known/*"
  	[headers.values]
    Access-Control-Allow-Origin = "*"
