backend:
  name: git-gateway
  branch: master

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: "essays"
    label: "Essays"
    label_singular: "Essay"
    folder: "content/essays"
    create: true
    slug: "essays/{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "created", widget: "datetime" }
      - { label: "Updated Date", name: "date", widget: "datetime" }
      - { label: "Published", name: "published", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Page Type", name: "pagetype", widget: "string", default: "https://schema.org/WebPage" }
      - label: "Item Type"
        name: "itemtype"
        widget: "select"
        options:
          - { label: "Article", value: "https://schema.org/Article"}
          - { label: "Blog Posting", value: "https://schema.org/BlogPosting"}
          - { label: "News Article", value: "https://schema.org/NewsArticle"}
          - { label: "Tech Article", value: "https://schema.org/TechArticle"}
        default: ["https://schema.org/BlogPosting"]
    sortable_fields: ['date', 'created', 'title']
  - name: "notes"
    label: "Notes"
    label_singular: "Note"
    folder: "content/notes"
    create: true
    slug: "notes/{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "created", widget: "datetime" }
      - { label: "Updated Date", name: "date", widget: "datetime" }
      - { label: "Published", name: "published", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Page Type", name: "pagetype", widget: "string", default: "https://schema.org/WebPage" }
      - label: "Item Type"
        name: "itemtype"
        widget: "select"
        options:
          - { label: "Article", value: "https://schema.org/Article"}
          - { label: "Blog Posting", value: "https://schema.org/BlogPosting"}
          - { label: "News Article", value: "https://schema.org/NewsArticle"}
          - { label: "Tech Article", value: "https://schema.org/TechArticle"}
        default: ["https://schema.org/BlogPosting"]
    sortable_fields: ['date', 'created', 'title']
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "created", widget: "datetime" }
      - { label: "Updated Date", name: "date", widget: "datetime" }
      - { label: "Published", name: "published", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Page Type", name: "pagetype", widget: "string", default: "https://schema.org/WebPage" }
      - label: "Item Type"
        name: "itemtype"
        widget: "select"
        options:
          - { label: "Article", value: "https://schema.org/Article"}
          - { label: "Blog Posting", value: "https://schema.org/BlogPosting"}
          - { label: "News Article", value: "https://schema.org/NewsArticle"}
          - { label: "Tech Article", value: "https://schema.org/TechArticle"}
        default: ["https://schema.org/BlogPosting"]
    sortable_fields: ['date', 'created', 'title']
